// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoltRide.Api.Data;

#nullable disable

namespace VoltRide.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530161001_InitialVoltRideSchema")]
    partial class InitialVoltRideSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("VoltRide.Api.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batterylevel");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("bikes");
                });

            modelBuilder.Entity("VoltRide.Api.Models.RentalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BikeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bikeid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endtime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("starttime");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("TEXT")
                        .HasColumnName("totalcost");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.ToTable("rentallogs");
                });

            modelBuilder.Entity("VoltRide.Api.Models.RentalLog", b =>
                {
                    b.HasOne("VoltRide.Api.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");
                });
#pragma warning restore 612, 618
        }
    }
}
